version: '0.0.{build}'
branches:
  only:
  - master
  
environment:
  nodejs_version: '14'
  USER:
    secure: y/JTG30ACk7z4Mfowp/PrA==
  PASS:
    secure: isX2igm46qOUBAXSHbz8S8ZEGv1IQMtBXBxyEclfR+U=

install:
  - ps: Install-Product node $env:nodejs_version
  - cd tribler_debug_ui\app && npm install
  - npm install -g @angular/cli
  - set PATH=C:\Python38-x64;C:\Python38-x64\Scripts;%PATH%
  - python -m pip install --upgrade pip

test_script:
  - node --version
  - npm --version
  - cd tribler_debug_ui\app && ng test --watch=false

build_script:
  - cd tribler_debug_ui\app && ng build --prod --base-href /debug-ui/
  - echo __version__ = '%APPVEYOR_BUILD_VERSION%' > tribler_debug_ui\__init__.py
  - python -m pip install wheel
  - python setup.py bdist_wheel
  
artifacts:
- path: dist\*.whl
  name: wheel

deploy_script:
  - ps: |
      if($env:APPVEYOR_REPO_TAG -eq 'true') {
        Write-Output ("Deploying " + $env:APPVEYOR_REPO_TAG_NAME + " to PyPI...")
        Invoke-Expression "python -m pip install twine"
        Invoke-Expression "python -m twine upload --repository testpypi -u ${Env:USER} -p ${Env:PASS} --skip-existing dist/*.whl"
      } else {
        Write-Output "No tag for deployment"
      }
